- name: Install config for kafkaserver
  template:
    src: server.properties.j2
    dest: /opt/kafka/config/kraft/server.properties

- name: Format Log Directories
  command: "/opt/kafka/bin/kafka-storage.sh format -t {{ kafka_cluster_id }} -c /opt/kafka/config/kraft/server.properties"
