- name: Add SPARK_LOCAL_IP to /etc/profile
  lineinfile:
    dest: /etc/profile
    state: present
    regexp: "^export SPARK_LOCAL_IP="
    line: "export SPARK_LOCAL_IP={{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"

- name: Install Jupyter pip packages
  pip:
    name:
      - jupyterlab
      - notebook
      - jupyterhub
    state: present

- name: Install Node.js dependecies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg

- name: Install Node.js gpg key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    state: present

- name: Add NodeSource APT repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} nodistro main"
    state: present
    filename: nodesource

- name: Install Node.js
  apt:
    name: nodejs
    state: present

- name: Install configurable-http-proxy npm package
  npm:
    name: configurable-http-proxy
    global: yes
    state: present

- name: Install data science pip packages
  pip:
    name:
      - beautifulsoup4
      - ipympl
      - ipywidgets
      - matplotlib
      - pandas==2.0.3
      - pyarrow
      - scikit-learn
      - scipy
    state: present

- name: Install supervisor
  apt:
    name: supervisor
    state: present

- name: Make sure supervisord is running
  service:
    name: supervisor
    enabled: yes
    state: started

- name: Run supervisord as root
  lineinfile:
    dest: /etc/supervisor/supervisord.conf
    state: present
    line: "user=root"
    insertafter: "^\[supervisord\]"

- name: Add student users
  user:
    name: "{{ item.name }}"
  with_items: "{{ student_users }}"

- name: Make sure /srv/jupyterhub exists
  file: 
    path: "{{ jupyterhub_srv_dir }}/" 
    state: "{{ item }}" 
    owner: root 
    group: root 
    mode: 0700
  with_items:
    - directory
    - touch

- name: Make sure /var/log/jupyterhub exists
  file: 
    path: "{{ jupyterhub_log_dir }}/"
    state: "{{ item }}" 
    owner: root 
    group: root 
    mode: 0755
  with_items:
    - directory
    - touch

- name: Install supervisor config for jupyterhub
  template:
    src: jupyterhub.conf.j2
    dest: /etc/supervisor/conf.d/jupyterhub.conf 
    owner: root 
    group: root 
    mode: 0600

- name: Load jupyterhub supervisor config
  supervisorctl: 
    name: jupyterhub
    state: present

- name: Restart jupyterhub with supervisor
  supervisorctl: 
    name: jupyterhub 
    state: restarted
