- name: Install Node.js dependecies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg

- name: Install Node.js gpg key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    state: present

- name: Add NodeSource APT repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} nodistro main"
    state: present
    filename: nodesource

- name: Install Node.js
  apt:
    name: nodejs
    state: present
