- name: Install supervisor
  apt:
    name: supervisor
    state: present

- name: Make sure supervisord is running
  service:
    name: supervisor
    enabled: yes
    state: started

- name: Install supervisor config for jupyterhub
  template:
    src: jupyterhub.conf.j2
    dest: /etc/supervisor/conf.d/jupyterhub.conf
