- name: Install supervisor
  apt:
    name: supervisor
    state: present

- name: Make sure supervisord is running
  service:
    name: supervisor
    enabled: yes
    state: started

- name: Install supervisor config for sparkmaster
  template:
    src: sparkmaster.conf.j2
    dest: /etc/supervisor/conf.d/sparkmaster.conf
