- name: Check Spark files existence
  stat:
    path: /opt/spark
  register: spark_check

- name: Download Spark files
  get_url:
    url: https://dlcdn.apache.org/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz
    dest: /opt
    timeout: 300
  when: not spark_check.stat.exists

- name: Extract Spark files
  unarchive:
    src: /opt/spark-3.5.0-bin-hadoop3.tgz
    dest: /opt/
    remote_src: yes
  when: not spark_check.stat.exists

- name: Rename directory
  command: mv /opt/spark-3.5.0-bin-hadoop3 /opt/spark
  when: not spark_check.stat.exists

- name: Add Spark environment to /etc/profile
  lineinfile:
    dest: /etc/profile
    state: present
    regexp: "^export {{ item.key }}="
    line: "export {{ item.key }}={{ item.value }}"
  with_items: "{{ spark_environment }}"

- name: Add SPARK_LOCAL_IP to /etc/profile
  lineinfile:
    dest: /etc/profile
    state: present
    regexp: "^export SPARK_LOCAL_IP="
    line: "export SPARK_LOCAL_IP={{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
