- name: Check Spark files existence
  stat:
    path: /opt/spark
  register: spark_check

- name: Download Spark files
  get_url:
    url: https://dlcdn.apache.org/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz
    dest: /opt
    timeout: 300
  when: not spark_check.stat.exists

- name: Extract Spark files
  unarchive:
    src: /opt/spark-3.5.0-bin-hadoop3.tgz
    dest: /opt/
    remote_src: yes
  when: not spark_check.stat.exists

- name: Rename directory
  command: mv /opt/spark-3.5.0-bin-hadoop3 /opt/spark
  when: not spark_check.stat.exists

- name: Add Spark environment to /etc/profile
  lineinfile:
    dest: /etc/profile
    state: present
    regexp: "^export {{ item.key }}="
    line: "export {{ item.key }}={{ item.value }}"
  with_items: "{{ spark_environment }}"

- name: Install PySpark pip dependencies
  pip:
    name:
      - pandas==2.0.3
      - pyarrow>=4.0.0
      - numpy>=1.15
    state: present

- name: Download Streaming + Kafka maven dependency
  maven_artifact:
    group_id: org.apache.spark
    artifact_id: spark-sql-kafka-0-10_2.12
    version: 3.5.1
    dest: /opt/spark/jars/spark-sql-kafka-0-10_2.12.jar
