- name: Check Spark files existence
  ansible.builtin.stat:
    path: /opt/spark
  register: spark_check

- name: Download Spark files
  get_url:
    url: https://dlcdn.apache.org/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz
    dest: /opt
    timeout: 300
  when: not spark_check.stat.exists

- name: Extract Spark files
  unarchive:
    src: /opt/spark-3.5.0-bin-hadoop3.tgz
    dest: /opt/
    remote_src: yes
  when: not spark_check.stat.exists

- name: Rename directory
  command: mv /opt/spark-3.5.0-bin-hadoop3 /opt/spark
  when: not spark_check.stat.exists

- name: Add SPARK_HOME to ~/.profile
  lineinfile:
    dest: ~/.profile
    state: present
    regexp: ^export SPARK_HOME=
    line: export SPARK_HOME=/opt/spark
  