- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day

- name: Install Git
  apt:
    name: git
    state: present

- name: Install OpenJDK 17 JDK
  apt:
    name: openjdk-17-jdk
    state: present

- name: Install Scala
  apt:
    name: scala
    state: present

- name: Install software-properties-common (required for adding PPAs)
  apt:
    name: software-properties-common
    state: present

- name: Add deadsnakes PPA for Python 3.11
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: Install Python 3.11
  apt:
    name: python3.11
    state: present

- name: Install Python 3.11 Distutils
  apt:
    name: python3.11-distutils
    state: present

- name: Set Python 3.11 as default for python3
  alternatives:
    link: /usr/bin/python3
    name: python3
    path: /usr/bin/python3.8
    priority: 1
    state: present

- name: Set Python 3.11 as default for python3
  alternatives:
    link: /usr/bin/python3
    name: python3
    path: /usr/bin/python3.11
    priority: 2

- name: Remove python3-apt package
  apt:
    name: python3-apt
    state: absent

- name: Install python3-apt package
  apt:
    name: python3-apt
    state: present

- name: Check if pip is installed in .local/bin
  ansible.builtin.stat:
    path: ~/.local/bin/pip
  register: pip_check

- name: Ensure pip for Python 3.11 is installed
  script: 
    src: https://bootstrap.pypa.io/get-pip.py
    executable: python3
  when: not pip_check.stat.exists
