- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day

- name: Install Git
  apt:
    name: git
    state: present

- name: Install OpenJDK 17 JDK
  apt:
    name: openjdk-17-jdk
    state: present

- name: Install Scala 2.12
  apt:
    deb: https://downloads.lightbend.com/scala/2.12.2/scala-2.12.2.deb
    state: present

- name: Install software-properties-common (required for adding PPAs)
  apt:
    name: software-properties-common
    state: present

- name: Add deadsnakes PPA for Python 3.11
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present

- name: Install Python 3.11
  apt:
    name: python3.11
    state: present

- name: Install Python 3.11 Distutils
  apt:
    name: python3.11-distutils
    state: present

- name: Check if pip is installed in /usr/local/bin
  stat:
    path: /usr/local/bin/pip
  register: pip_check

- name: Download pip install script
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
  when: not pip_check.stat.exists

- name: Ensure pip for Python 3.11 is installed
  shell: curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11
  when: not pip_check.stat.exists
