---
- name: Install all Spark dependencies
  hosts: all
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes

    - name: Install OpenJDK 17 JDK
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Scala
      apt:
        name: scala
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install software-properties-common (required for adding PPAs)
      apt:
        name: software-properties-common
        state: present

    - name: Add deadsnakes PPA for Python 3.11
      apt_repository:
        repo: ppa:deadsnakes/ppa
        state: present

    - name: Install Python 3.11
      apt:
        name: python3.11
        state: present

    - name: Download Spark files
      get_url:
        url: "https://dlcdn.apache.org/spark/spark-3.5.0/spark-3.5.0-bin-hadoop3.tgz"
        dest: "/opt"
        timeout: 300

    - name: Extract Spark files
      unarchive:
        src: "/opt/spark-3.5.0-bin-hadoop3.tgz"
        dest: "/opt/"
        remote_src: yes

    - name: Rename Spark directory using mv command
      command: mv /opt/spark-3.5.0-bin-hadoop3 /opt/spark
