---
- name: Install all Spark dependencies
  hosts: all
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes

    - name: Install OpenJDK 17 JDK
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Scala
      apt:
        name: scala
        state: present

    - name: Install Git
      apt:
        name: git
        state: present
